name: tema5
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^1.2.1

  cupertino_icons: ^1.0.0
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: Cormorant Infant
      fonts:
        - asset: assets/fonts/CormorantInfant-bold.ttf
        - asset: assets/fonts/CormorantInfant-LightItalic.ttf
          style: normal